# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNgram',
            fields=[
                ('ArticleNgramId', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.IntegerField(default=0)),
                ('StdFrequency', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('ArticleId', models.AutoField(primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=20)),
                ('RawText', models.TextField()),
                ('ProcessedText', models.TextField(blank=True)),
                ('WordCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('ArticleNgramId', models.IntegerField(primary_key=True, serialize=False)),
                ('ArticleId_id', models.IntegerField(default=0)),
                ('NgramId_id', models.IntegerField(default=0)),
                ('Frequency', models.IntegerField(default=0)),
                ('WordCount', models.IntegerField(default=0)),
                ('StdFrequency', models.FloatField(default=0)),
                ('Source', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ngram',
            fields=[
                ('NgramId', models.AutoField(primary_key=True, serialize=False)),
                ('Ngram', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='articlengram',
            name='ArticleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicsApp.Articles'),
        ),
        migrations.AddField(
            model_name='articlengram',
            name='NgramId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicsApp.Ngram'),
        ),
    ]
